apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: beam-flink-cluster
spec:
  flinkVersion: 1.8.1
  image:
    name: flink:1.8.1
  taskManager:
    replicas: 2
    sidecars:
      - name: beam-worker-pool
        image: apachebeam/python3.7_sdk:2.18.0
        args: ["--worker_pool"]
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"
